version: '3.8'

services:
  gatsby-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: gatsby-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: npm run develop -- -H 0.0.0.0 